name: Build

on:
  push:
    branches:
      - work
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build
        run: ./gradlew :retro-music:assembleRelease

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: LyricProvider-APKs
          path: '**/build/outputs/apk/**/*.apk'
